# Generated by Django 4.2 on 2023-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_downloader', '0003_downloadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedfile',
            name='status',
            field=models.CharField(default='In progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadedfile',
            name='content',
            field=models.FileField(upload_to='files/'),
        ),
    ]
