# Generated by Django 4.2 on 2023-04-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_downloader', '0005_downloadedfile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
